# Generated by Django 3.0.7 on 2021-06-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=100, verbose_name='Vaga')),
                ('salario', models.CharField(choices=[('s1', 'Até R$ 1.000,00'), ('s2', 'De R$ 1.000,00 a 2.000,00'), ('s3', 'De R$ 2.000,00 a 3.000,00'), ('s4', 'Acima de R$ 3.000,00')], max_length=90)),
                ('escolaridade', models.CharField(choices=[('e1', 'Ensino fundamental'), ('e2', 'Ensino médio'), ('e3', 'Tecnólogo'), ('e4', 'Ensino Superior'), ('e5', 'Pós / MBA / Mestrado'), ('e6', 'Doutorado')], max_length=100)),
            ],
        ),
    ]
