# Generated by Django 3.0.7 on 2021-06-15 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='candidatos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='requisitos',
            field=models.TextField(default=1, verbose_name='Requisitos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='escolaridade',
            field=models.CharField(choices=[('e1', 'Ensino fundamental'), ('e2', 'Ensino médio'), ('e3', 'Tecnólogo'), ('e4', 'Ensino Superior'), ('e5', 'Pós / MBA / Mestrado'), ('e6', 'Doutorado')], max_length=100, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.CharField(choices=[('s1', 'Até R$ 1.000,00'), ('s2', 'De R$ 1.000,00 a 2.000,00'), ('s3', 'De R$ 2.000,00 a 3.000,00'), ('s4', 'Acima de R$ 3.000,00')], max_length=90, verbose_name='Salário'),
        ),
    ]
