# Generated by Django 3.0.7 on 2021-06-15 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210615_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='candidatos',
        ),
        migrations.AddField(
            model_name='vaga',
            name='candidatos',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
