# Generated by Django 3.0.7 on 2021-06-15 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210615_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='candidatos',
        ),
        migrations.CreateModel(
            name='Candidaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vaga')),
            ],
        ),
    ]
