# Generated by Django 3.0.7 on 2021-06-15 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20210615_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidaturas',
            new_name='Candidatura',
        ),
    ]
