# Generated by Django 3.0.7 on 2021-06-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210615_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data_publicacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da publicação'),
        ),
    ]
