# Generated by Django 3.0.7 on 2021-06-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vaga_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='data_candidatura',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da candidatura'),
        ),
    ]
