# Generated by Django 3.0.7 on 2021-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vaga_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='curso',
            field=models.CharField(default=1, max_length=100, verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatura',
            name='pontos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatura',
            name='pretensao_salarial',
            field=models.CharField(choices=[('Até R$ 1.000,00', 'Até R$ 1.000,00'), ('De R$ 1.000,00 a 2.000,00', 'De R$ 1.000,00 a 2.000,00'), ('De R$ 2.000,00 a 3.000,00', 'De R$ 2.000,00 a 3.000,00'), ('Acima de R$ 3.000,00', 'Acima de R$ 3.000,00')], default=1, max_length=90, verbose_name='Pretensão salarial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatura',
            name='ultima_escolaridade',
            field=models.CharField(choices=[('Ensino fundamental', 'Ensino fundamental'), ('Ensino médio', 'Ensino médio'), ('Tecnólogo', 'Tecnólogo'), ('Ensino Superior', 'Ensino Superior'), ('Pós / MBA / Mestrado', 'Pós / MBA / Mestrado'), ('Doutorado', 'Doutorado')], default=1, max_length=100, verbose_name='Última escolaridade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='escolaridade',
            field=models.CharField(choices=[('Ensino fundamental', 'Ensino fundamental'), ('Ensino médio', 'Ensino médio'), ('Tecnólogo', 'Tecnólogo'), ('Ensino Superior', 'Ensino Superior'), ('Pós / MBA / Mestrado', 'Pós / MBA / Mestrado'), ('Doutorado', 'Doutorado')], max_length=100, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.CharField(choices=[('Até R$ 1.000,00', 'Até R$ 1.000,00'), ('De R$ 1.000,00 a 2.000,00', 'De R$ 1.000,00 a 2.000,00'), ('De R$ 2.000,00 a 3.000,00', 'De R$ 2.000,00 a 3.000,00'), ('Acima de R$ 3.000,00', 'Acima de R$ 3.000,00')], max_length=90, verbose_name='Salário'),
        ),
    ]
