# Generated by Django 3.0.7 on 2021-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210616_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='experiencia',
            field=models.TextField(default=1, verbose_name='Experiência'),
            preserve_default=False,
        ),
    ]
