# Generated by Django 3.0.7 on 2021-06-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_candidatura_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='candidaturas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Candidaturas para essa vaga'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='pretensao_salarial',
            field=models.CharField(max_length=90, verbose_name='Pretensão salarial'),
        ),
    ]
