# Generated by Django 3.0.7 on 2021-06-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210616_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name='Data da publicação'),
        ),
    ]
