# Generated by Django 3.0.7 on 2021-06-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_userprofile_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, upload_to='media/cvs/', verbose_name='Currículo'),
        ),
    ]
