# Generated by Django 3.0.7 on 2021-06-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210613_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sobrenome',
        ),
    ]
