# Generated by Django 3.0.7 on 2021-06-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20210618_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cv',
        ),
    ]
