# Generated by Django 3.0.7 on 2021-06-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_userprofile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, default='media/default-profile.png', upload_to='media', verbose_name='Foto'),
        ),
    ]
