# Generated by Django 3.0.7 on 2021-06-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20210618_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, default='default-profile.png', upload_to='media', verbose_name='Foto'),
        ),
    ]
